### ISSUE TITLE
Error "No such device""

### ISSUE THREAD

**Issue by ghost** [ctrlcctrlv/QKeysOnScreen#6]
After apply new window size (height `100`; width `200`) throw "Set window size..."  dialog, QKOS stopped to showing/logging input keys (not sure what happen).

Just after restart QKOS all seems work as expected, so can't reproduce it again.

![pic.1](https://i.imgur.com/S00hMMc.png)

### Terminal Log

```
$ sudo ./QKeysOnScreen
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
True
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "./QKeysOnScreen", line 611, in run
    for event in self.devicesdict[fd].read():
  File "/usr/lib/python3/dist-packages/evdev/eventio.py", line 71, in read
    events = _input.device_read_many(self.fd)
OSError: [Errno 19] No such device
```

**Comment by ctrlcctrlv** [comment]
Closed as irreproducible.
